---
title: "Tesis Montserrat"
author: "Juan Carlos Martinez-Ovando"
date: "15 June 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Comentarios

* En la `Introduccion` elabora una argumentacion de los dos tipos de enfoques para clasificacion no supervisada:
 
a. Basado en argumentos geometricos (o distancias)

b. Basado en distribuciones (o modelos)

Discute sobre tu interpretacione de las ventajas y desventajas implicitas...

* Ec. (2.1) - La ecuacion hace referencia al caso *i.i.d.*, solo independencia referiria a considerar $P_j(x_j)$ (i.e. indizada por $j$ en cada )

* Mueve la seccion `Distribucion predictiva` despues de las secciones `Distribucion inicial` y `Distribucion posterior` en el capitulo 2

* El capitulo 3 refierelo a `Clasificacion basada en modelos`

* Define las tres secciones que tienes como Secciones no Subsecciones

* Incorpora la siguienes secciones a este capitulo: 

3.4. Inferencia bayesiana en modelos de mezclas

3.5. Prediccion (numerica)

* El capitulo 4 que sea `Clasificacion con datos discretos y continuos`

4.1. Revision de propuestas

4.2. Especificacion del kernel

4.2.1. Parte discreta

4.2.2. Parte continua

4.3. parametris y distribucion inicial

4.4. Gibbs sampler

4.4.1 Distribucion final completa...

So on...

* Capitulo 5 `Aplicacion`

* Capitulo 6 `Conclusiones`

Referencias

* Apendice 1. Gibbs sampler (teoria)

* Apendice 2. Distribuciones
